[package]
name = "borrow"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
swc_common = "0.23.0"
swc_ecma_parser = "0.134.0"
swc_ecma_ast = "0.104.0"